# Generated by Django 4.0.6 on 2022-07-11 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_code_maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipmentcode',
            options={},
        ),
        migrations.AlterModelTable(
            name='equipmentcode',
            table=None,
        ),
    ]
