# Generated by Django 4.1b1 on 2022-07-21 15:06

from django.db import migrations, models
import django.db.models.manager
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "Userrole",
                    models.CharField(
                        choices=[
                            ("External User", "Ext_user"),
                            ("Internal User", "Int_user"),
                            ("Standard User", "basic_user"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "UserID",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                ("FirstName", models.CharField(blank=True, max_length=100)),
                ("LastName", models.CharField(blank=True, max_length=100)),
                (
                    "PrimaryNumber",
                    phone_field.models.PhoneField(
                        blank=True, max_length=31, verbose_name="Contact phone number"
                    ),
                ),
                (
                    "EmailAddress",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Email Address"
                    ),
                ),
                (
                    "Company",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Company Name"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_admin", models.BooleanField(default=False)),
                (
                    "date_joined",
                    models.DateField(auto_now_add=True, verbose_name="Created Date"),
                ),
                (
                    "date_modified",
                    models.DateField(auto_now=True, verbose_name="Last Modified Date"),
                ),
            ],
            options={
                "db_table": "URI_UserMaintenance",
            },
            managers=[
                ("cus_user", django.db.models.manager.Manager()),
            ],
        ),
    ]
