# Generated by Django 4.1 on 2022-08-03 17:38

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='proj_expense',
            fields=[
                ('ExpenseCodeID', models.AutoField(primary_key=True, serialize=False)),
                ('ExpDescription', models.CharField(max_length=100, verbose_name='Project Expense Class')),
                ('ExpBillingCode', models.CharField(max_length=20, verbose_name='Billing Codes')),
                ('ExDefaultRates', models.IntegerField(blank=True, default=0, null=True, verbose_name='Default Rate')),
                ('ExpActive', models.BooleanField(choices=[(0, 'Deactive'), (1, 'Acactive')], default=True, verbose_name='Active Status')),
                ('LastUpdatedBy', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'URI_projexpense',
            },
            managers=[
                ('proj_exp', django.db.models.manager.Manager()),
            ],
        ),
    ]
