# Generated by Django 4.1 on 2022-08-03 17:38

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMaintenance',
            fields=[
                ('ProjectID', models.AutoField(primary_key=True, serialize=False)),
                ('ProjectName', models.CharField(max_length=100, verbose_name='Project Name')),
                ('ProjectLocation', models.CharField(blank=True, help_text='(Street, City, State and Zip code)', max_length=128, null=True, verbose_name='Project Location')),
                ('ProjectDuration', models.DurationField(blank=True, verbose_name='Project Duration')),
                ('ProjectManager', models.IntegerField(blank=True, null=True, verbose_name='Project Manager')),
                ('PJDateCreated', models.DateField(auto_now_add=True, verbose_name='Date Created')),
                ('PJLastModifiedOn', models.DateField(auto_now=True, verbose_name='Date Modified')),
                ('LastUpdatedBy', models.IntegerField(blank=True, null=True)),
            ],
            managers=[
                ('dj_project_maintenance', django.db.models.manager.Manager()),
            ],
        ),
    ]
