# Generated by Django 4.0.6 on 2022-07-18 12:45

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='labor_code',
            fields=[
                ('LaborCodeID', models.AutoField(primary_key=True, serialize=False)),
                ('LCDescription', models.CharField(max_length=100, verbose_name='Labor Class')),
                ('LCBillingCode', models.CharField(max_length=20, verbose_name='Billing Codes')),
                ('LCDefaultRates', models.IntegerField(blank=True, default=0, null=True)),
                ('LCActive', models.BooleanField(choices=[(0, 'Deactive'), (1, 'Active')], default=True)),
                ('LastUpdatedBy', models.CharField(default='John', max_length=100)),
            ],
            options={
                'db_table': 'labor_code',
            },
            managers=[
                ('labor_code', django.db.models.manager.Manager()),
            ],
        ),
    ]
